Repository PedroChaparro/loomies-mobile, pull requests merged in 2023-05, with the labels that each got.

#88 Change loomie in combat
  src/components/Combat/CombatUI.tsx
  src/components/Modals/Combat/LoomieCombatCard.tsx
  src/components/Modals/Combat/LoomiesCombatGrid.tsx
  src/components/Modals/Combat/SelectLoomieModal.tsx
  src/pages/CombatView.tsx
  src/types/combatInterfaces.ts
Labels: frontend, loomie inventory, battle

#89 Feat: 3D item models
  assets/images/items/001.png
  assets/images/items/002.png
  assets/images/items/003.png
  assets/images/items/004.png
  assets/images/items/005.png
  assets/images/items/006.png
  assets/images/items/007.png
  assets/images/items/008.png
  assets/images/items/009.png
  assets/images/items/010.png
  assets/images/items/resizeBulk.sh
  assets/models/loomballs/loomball1.glb
  assets/models/loomballs/loomball2.glb
  assets/models/loomballs/loomball3.glb
  assets/modelsSource/items/items.blend
  assets/modelsSource/items/textures/Layer 0_mat_defibrillator_body.png
  assets/modelsSource/items/textures/Layer 0_mat_defibrillator_handle1.png
  assets/modelsSource/items/textures/Layer 0_mat_vitaminsLid.png
  assets/modelsSource/items/textures/Layer 0_mat_vitaminsSticker.png
  assets/modelsSource/items/textures/Layer 1_mat_defibrillator_body.png
  assets/modelsSource/items/textures/Layer 1_mat_vitaminsSticker.png
  assets/modelsSource/items/textures/Layer 2_mat_defibrillator_body.png
  assets/modelsSource/items/textures/tex_bigAidKit_layer0.png
  assets/modelsSource/items/textures/tex_bigAidKit_layer1.png
  assets/modelsSource/items/textures/tex_potionSticker.png
  assets/modelsSource/items/textures/tex_smallAidKit_bottle1_layer0.png
  assets/modelsSource/items/textures/tex_smallAidKit_bottle1_layer1.png
  assets/modelsSource/items/textures/tex_smallAidKit_bottle1_layer2.png
  assets/modelsSource/items/textures/tex_smallAidKit_pot0_layer1.png
  assets/modelsSource/items/textures/tex_smallAidKit_pot0_layer2.png
  assets/modelsSource/items/textures/tex_speedshot_sticker_layer0.png
  assets/modelsSource/items/textures/tex_speedshot_sticker_layer1.png
  assets/modelsSource/items/textures/tex_speedshot_sticker_layer2.png
  assets/modelsSource/items/textures/tex_strengthShot_sticker_layer0.png
  assets/modelsSource/items/textures/tex_strengthShot_sticker_layer1.png
  assets/modelsSource/items/textures/tex_strengthShot_sticker_layer2.png
  assets/modelsSource/items/textures/tex_syringe1.png
  assets/modelsSource/items/textures/tex_syringe2.png
  assets/modelsSource/items/textures/tex_syringe3.png
  assets/modelsSource/loomballs/loomball/loomball.blend
  assets/modelsSource/loomballs/loomball/tex_Layer0.png
  assets/modelsSource/loomballs/loomball/tex_Layer1.png
  assets/modelsSource/loomballs/loomball/tex_Layer2.png
  assets/modelsSource/loomballs/loomballs.blend
  assets/modelsSource/loomballs/textures/tex_loomball2_layer0.png
  assets/modelsSource/loomballs/textures/tex_loomball2_layer1.png
  assets/modelsSource/loomballs/textures/tex_loomball3_layer0.png
  assets/modelsSource/loomballs/textures/tex_loomball3_layer1.png
  assets/modelsSource/loomballs/textures/tex_loomball3_layer2.png
  assets/modelsSource/loomballs/textures/tex_loomball_layer0.png
  assets/modelsSource/loomballs/textures/tex_loomball_layer1.png
  src/components/CaptureLoomie3D/CaptureLoomie3D.tsx
  src/components/CaptureLoomie3D/CaptureSM.ts
  src/pages/CaptureView.tsx
Labels: frontend, item inventory, capture screen, 3D

#87 Feat: Modal to congrats capture
  src/components/CaptureLoomie3D/CaptureLoomie3D.tsx
  src/components/CaptureLoomie3D/utilsAnimations.ts
  src/components/LoomieDetails/LoomieRarityTag.tsx
  src/components/MapElementManager/MapElementManager.tsx
  src/components/Modals/Capture/ModalCongratsCapture.tsx
  src/components/Modals/Gyms/ModalGym.tsx
  src/context/GymsModalContext.tsx
  src/context/MapModalsProvider.tsx
  src/navigation/StackNavigation.tsx
  src/pages/MapView.tsx
Labels: frontend, capture screen

#90 Feat: Navbar and App icon
  android/app/src/main/res/ic_launcher-web.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-ldpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/playstore-icon.png
  android/app/src/main/res/values/ic_launcher_background.xml
  src/navigation/BottomNavigation.tsx
Labels: frontend

#91 Style: Floating buttons
  src/components/CaughtLoomiesGrid/LoomiesGrid.tsx
  src/components/FloatingRedIcon.tsx
  src/components/Modals/Combat/SelectLoomieModal.tsx
  src/components/Modals/FuseLoomiesModal.tsx
  src/components/Modals/SelectLoomBall.tsx
  src/pages/UpdateLoomieTeamView.tsx
  src/pages/UserLoomies.tsx
Labels: frontend

#92 Feat: Update gyms protectors
  src/components/EmptyMessage.tsx
  src/components/Modals/Gyms/ModalGym.tsx
  src/components/Modals/Gyms/ModalUpdateProtectors.tsx
  src/components/Modals/UseItem.tsx
  src/context/MapModalsProvider.tsx
  src/pages/MapView.tsx
  src/services/gyms.services.ts
Labels: frontend, gymnasium

#94 Feat: User actions cooldown
  src/components/Combat/CombatUI.tsx
  src/components/Modals/Combat/SelectLoomieModal.tsx
  src/pages/CombatView.tsx
Labels: frontend, battle

#96 Fix: Texts overflows
  src/components/Combat/CombatUI.tsx
  src/components/Combat/combatStyles.ts
  src/components/Modals/Gyms/ModalGym.tsx
  src/pages/Profile.tsx
Labels: frontend

#98 Fix: Improved Combat UX
  src/components/Combat/Combat3D/CombatSM.ts
  src/components/Combat/CombatUI.tsx
  src/components/Combat/combatStyles.ts
  src/pages/CombatView.tsx
  src/types/combatInterfaces.ts
Labels: battle, 3D

#99 Feat: Loomie capture scene AR support
  src/components/CaptureLoomie3D/CaptureLoomie3D.tsx
  src/components/CaptureLoomie3D/CaptureSM.ts
  src/components/CaptureLoomie3D/animations.ts
  src/components/CaptureLoomie3D/utilsAnimations.ts
  src/pages/CaptureView.tsx
Labels: frontend, AR, capture screen, 3D
